export enum AppErrorCode {
  DISCORD_CHANNEL_NOT_FOUND = "DISCORD_CHANNEL_NOT_FOUND",
  DISCORD_EMBED_DESCRIPTION_TOO_LONG = "DISCORD_EMBED_DESCRIPTION_TOO_LONG",
  DISCORD_MESSAGE_CONTENT_TOO_LONG = "DISCORD_MESSAGE_CONTENT_TOO_LONG",
}
