export enum AppErrorCode {
  DISCORD_CARD_DESCRIPTION_TOO_LONG = "DISCORD_CARD_DESCRIPTION_TOO_LONG",
  DISCORD_CHANNEL_NOT_FOUND = "DISCORD_CHANNEL_NOT_FOUND",
  DISCORD_MESSAGE_CONTENT_TOO_LONG = "DISCORD_MESSAGE_CONTENT_TOO_LONG",
}
